### ISSUE TITLE
The results were not the same

### ISSUE THREAD

**Issue by wangzhennan14** [rmhubley/RepeatModeler#11]
Hi,
   I used RepeatModeler to find repeat regions on one genome, I have run RepeatModeler twice. But the result, consensi.fa.classified, have different sequences. Which result I can use to run RepeatMasker? And why the results is different? Please give me some advice to solve this problem. Thank you very much!
   Best wishes.

                                                                                                                             Wang

**Comment by rmhubley** [comment]
RepeatModeler employs a random sampling strategy.  Each run of RepeatModeler will sample different sets of sequences unless you explicitly set the "-srand #" flag.  At the start of each run the seed is printed to the screen so that any given run may be reproduced by using the srand option with that number.  While the files from two different sampled runs will not be exactly the same the families generated are essentially so.
