### ISSUE TITLE
rmblast make install error found

### ISSUE THREAD

**Issue by zx0223winner** [rmhubley/RepeatModeler#17]
Hi RepeatModeler supporting team,

I met the same problem on the rmblast installation which could be found in former quote.
[https://github.com/rmhubley/RepeatModeler/issues/5](url)

Honestly, I followed some suggestions from the former quote, however I still could not successfully install the RepeatModeler engine(i.e.,  rmblast  ) 

Will appreciate for any suggestions! Below is the report after running.

> $ sudo make install
 if test -d /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then \
    make  install-gbench; \
else \
    make  install-toolkit; \
fi
make[1]: Entering directory '/home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++'
/bin/rm -rf /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install -c -d /usr/local/rmblast/bin /usr/local/rmblast/lib /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install -c /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /usr/local/rmblast/bin
/usr/bin/install -c -m 644 /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/*.* /usr/local/rmblast/lib
if test -d /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \
    cp -pPR /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /usr/local/rmblast/lib/; \
fi
rm -f /usr/local/rmblast/lib/lib*-static.a
cd /usr/local/rmblast/lib  && \
    for x in *.a; do \
        /bin/ln -s "$x" "`/usr/bin/basename \"$x\" .a`-static.a"; \
    done
cd /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\
            cpio -pd /usr/local/rmblast/include/ncbi-tools++
51192 blocks
/usr/bin/install -c -m 644 /home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/* /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install: omitting directory '/home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common'
Makefile:40: recipe for target 'install-toolkit' failed
make[1]: *** [install-toolkit] **Error 1**
make[1]: Leaving directory '/home/zxwinner/Desktop/software/genome_masking/RepeatModeler/ncbi-blast-2.6.0+-src/c++'
Makefile:62: recipe for target 'install' failed
make: *** [install] **Error 2**

**Comment by darcyabjones** [comment]
Sorry to revive an old issue.
I just ran into the same `Makefile:40: recipe for target 'install-toolkit' failed` problem myself.

The problem that was originally posted was caused because `install` doesn't know what to do with directories.
Hence the `omitting directory` line.

As suggested in #5 the binaries etc in the ReleaseMT directory will work.
So you could just set your `PATH` etc there if you don't mind having the compilation intermediates hanging around and taking up space.

The `ReleaseMT/inc` directory just has a single headerfile and the `common` directory.
You can get the install command to finish by editing the Makefile to use a more specific glob pattern `*.h` and then run a separate install command for the files in `common`.

Here are some `sed` commands that will do this for you, assuming you're in the c++ directory.

```bash
sed -i '/$(INSTALL) -m 644 $(incdir)\/\* $(pincludedir)/ i \\t$(INSTALL) -m 644 $(incdir)/common/* $(pincludedir)/common' Makefile
sed -i '/$(INSTALL) -m 644 $(incdir)\/\* $(pincludedir)/ s/\*/\*.h/' Makefile
```
Hope this helps the next person that comes across this.

Darcy

**Comment by rmhubley** [comment]
There are a few problems listed here.  The path confusion with the RepeatMasker's configure script was due to the way the script prompted for input.  It should have been more specific that it was looking for the path to the directory containing the executable.  In the next release of RepeatMasker the configure script is smarter about how it locates dependencies.  The other problem:

Makefile:62: recipe for target 'install' failed
make: *** [install] Error 2

is a problem with the NCBI Toolkit but didn't seem indicate a real failure.  When we ran "make install" it simply did the place the required files in the installation directory but returned this failure regardless.  We are about to release RMBlast 2.9.  It seems NCBI must have fixed this problem as it no longer returns this error code.
