### ISSUE TITLE
edgeredef failed (RECON)

### ISSUE THREAD

**Issue by JennyHTLee** [rmhubley/RepeatModeler#18]
Hi,

I encountered a RECON error when running RepeatModeler and could not resolve it:

       edgeredef failed. Exit code 1024

The error persists even after reinstalling RECON 1.08 and reconfiguring RepeatModeler and RepeatMasker.
Below are snippets from log files and program versions, any ideas would be greatly appreciated!

Cheers, 
Jenny

```shell
#Last lines of my log file
Comparison Time: 00:15:04 (hh:mm:ss) Elapsed Time, 75366 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running initial definition of elements ( eledef )..
RECON Elapsed: 00:06:06 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of elements ( eleredef )..
RECON Elapsed: 00:52:31 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of edges ( edgeredef )..
edgeredef failed. Exit code 1024

#Last 10 lines of round-4/edge_redef_res/log
evaluating edges of element 22289
new clan: 10402 for ele 22289
clan size: 4, clan core size: 1
evaluating edges of element 22290
evaluating edges of element 22291
evaluating edges of element 22292
evaluating edges of element 22293
evaluating edges of element 22294
evaluating edges of element 22295
error:  more edges in file for ele 22295
```

Versions:
RECON 1.08
RepeatMasker open-4.0.7
RepeatModeler  open-1.0.11
RepeatScout 1.0.5
RMBlast 2.2.27+; Package: rmblastn 2.2.28, build Jun 23 2018 12:40:24

**Comment by rmhubley** [comment]
Hi Jenny. I’m traveling right now but I’ll take a look at this when I get
back. Could you tar up the round-4 directory and send it to me?

**Comment by JennyHTLee** [comment]
Hi Robert,

Thanks for replying, 
Attached is the link to my round-4 dir: https://cloudstor.aarnet.edu.au/plus/s/m0CFmP7UlJV4tNP

Cheers,
Jenny

**Comment by JennyHTLee** [comment]
Just to update,

I repeat the same commands per scaffold as a workaround and the edgeredef error never came up, RepeatModeler and RepeatMasker for all scaffolds completed successfully.

Perhaps this error is memory/IO related?

Cheers,
Jenny

**Comment by rmhubley** [comment]
I had my head down in work for a bit.  I didn't write RECON but I have fixed a few bugs surface with rare edge cases.  This exit code is not useful because it's just indicating that edgeredef probably segfaulted.  I am not sure what you mean by "repeated the same commands per scaffold".  If you mean that you repeated the RepeatModeler run ( with using the -srand parameter ) then RepeatModeler generates a completely different random sample and I can understand why RECON might not exhibit the same behaviour ( edge case that I was referring to ).  If you ran edgeredef by hand on the same dataset ( RM_*/round-4/edge_redef_res ... ) then it's more likely a problem with the system.

Sorry I couldn't be more specific in this case.  Let me know if you have further problems.
