### ISSUE TITLE
MultAln::buildConsensusFromArray: Matrix alphabet doesn't include the letters: A, B

### ISSUE THREAD

**Issue by zjlahey** [rmhubley/RepeatModeler#2]
Encountered the following issue:

RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 40000844 bp ( 39718874 non ambiguous )
   - Num Contigs Represented = 14077
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..
   - RepeatScout: Running RepeatScout..
Program duration is 565.0 sec = 9.4 min = 0.2 hr
   - Collecting repeat instances...
 -- Refining Family R=728 / 0 ( RS Elements: 664, Using 100 ):
MultAln::buildConsensusFromArray: Matrix alphabet doesn't include
the letters: A, B
 at /users/PAS0615/osu8353/RepeatModeler/Refiner line 395.
RepeatModeler: Could not open refined model /users/PAS0615/osu8353/RepeatModeler                                       /RM_31461.MonMay220946262017/round-1/family-0.fa.refiner_cons!

I am using RepeatModeler Version open-1.0.10 from the repeatmasker webpage. Should I try with the git release of repeatmodeler?

Thanks!

**Comment by rmhubley** [comment]
You have a "D" and "B" in your input genome somewhere.  These are IUB codes that represent an uncalled base as possibly one of three particular nucleotides.   The matrices used by RepeatModeler do not currently support these three-way degenerative symbols.  The easiest thing to do would be to replace "D", "V", "H", and "B" in your input sequence with "N".  It is pretty atypical that a base caller/assembler would use these codes rather than simply using "N".   Where did your input sequences come from?

**Comment by zjlahey** [comment]
Thanks for the reply. The reads used to assemble this genome are from 454 Life Sciences. I think they did the sequencing in 2007, but I'm not sure. I will make the changes and let you know how it goes. Thank you very much, I should have caught that.

**Comment by ckeeling** [comment]
I have the same issue:

``MultAln::buildConsensusFromArray: Matrix alphabet doesn't include
the letters: A, H``

This is on an assembly that was improved by using [abyss-sealer](https://github.com/bcgsc/abyss/tree/master/Sealer), which uses all the ambiguous codes.  Usually they appear singly rather than in stretches.

Your above suggestion of replacing these with N should not really make much difference for RepeatModeller's results, right?

**Comment by rmhubley** [comment]
Don't replace "A"s with "N" for obvious reasons.  Just convert the "H" letters.  These 3 way ambiguity codes are useless for this type of analysis.  I need to change the wording of this error message to indicate that the matrix doesn't contain one of the two aligned bases ( e.g in this case A->H ).

**Comment by petrelharp** [comment]
It would also be nice if the error message said that those letters were found in the sequence.
