### ISSUE TITLE
The DNA content of consensi.fa and consensi.fa.classified is different

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [rmhubley/RepeatModeler#29]
Hello, I didn't find any documentation about the difference between the files `consensi.fa` and `consensi.fa.classified`, but when I analyze their content it seems that the file `consensi.fa.classified` has the same entries than `consensi.fa` but with additional information in headers (like `#DNA/TcMar-Tc1`). But when I compare the entries, I see that the the headers appear in the same order in both files, but in some cases the DNA sequence changes between the files. Is it normal? If so, could it be possible to explain why does it happen?

**Comment by rmhubley** [comment]
That doesn't sound right.  Could you send me both files so I can take a closer look? rhubley@systemsbiology.org

**Comment by SvitlanaLukicheva** [comment]
Thank you for your prompt reply, I just sent you the files.

**Comment by rmhubley** [comment]
Thanks for the files.  What you are noticing is RepeatClassifier reverse-complementing families that have been classified using homology to existing families.  If the consensus is found to be reversed it corrects them automatically.    For instance:

This is the same between the two files as it could not be classified so either direction is just as likely.
>rnd-1_family-471#Unknown ( RepeatScout Family Size = 132, Final Multiple Alignment Size = 100, Localized to 1140 out of 1171 contigs )

While the next one was found to match a DNA transposon family and aligned in the opposite direction.
>rnd-1_family-21#DNA/CMC-Transib ( RepeatScout Family Size = 4917, Final Multiple Alignment Size = 100, Localized to 1140 out of 1171 contigs )

Otherwise there weren't any sequence differences between these two files.

-R

**Comment by SvitlanaLukicheva** [comment]
Right, thank you very much!
