### ISSUE TITLE
Clarification on rmblastn parameters

### ISSUE THREAD

**Issue by darencard** [rmhubley/RepeatModeler#4]
I'm trying to better understand what rmblastn search parameters are being used within RepeatModeler, since the RepeatModeler option names aren't exact the same as they are in rmblastn. Basically, if I wanted to call rmblastn myself from the shell, what command would I issue to repeat the same search being performed within RepeatModeler?

I've picked out a lot of these by matching them to the rmblastn help, but there are a few lingering ones that I'm unsure about. Here is a list of all options I can find within RepeatModeler for an NCBI search and my guess as to the rmblastn option. With any option not listed, I'm assuming default rmblastn values are used (but let me know if that's somehow incorrect). Also, the values assigned to each option appear to speak for themselves, and aren't derived on the fly based on the dataset. If you could clarify where necessary, I would greatly appreciate it.

```
setQuery == -query
setSubject == -subject (or -db ???, not sure what difference is)
setMinScore == -min_raw_gapped_score (??)
setMatrix == -matrix /path/to/RepeatModeler/Matrices/ncbi/nt/comparison.matrix
setGenerateAlignments == -outfmt 0 (??)
setGapInit == -gapopen
setBandwidth == ??
setInsGapExt == -gapextend
setDelGapExt == ??
setMinMatch == ??
setScoreMode( SearchEngineI::complexityAdjustedScoreMode ) == -complexity_adjust
setMaskLevel == -mask_level
setAdditionalParameters == additional command-line arguments to rmblastn
     -gilist == -gilist
     dbslice == ??
     -gapW == ??
```

**Comment by rmhubley** [comment]
Happy to help.  You are comparing the generic "SearchEngine" interface defined by RepeatMasker with the concrete implementation defined by the NCBIBlastSearchEngine object (RepeatMasker/NCBIBlastSearchEngine.pm).  I will annotate your table with what can be found in that RepeatMasker module:

Query Parameters:
setQuery == -query
setSubject == -db
    The definition of query/subject can vary between use-cases.  The terms were adopted from the Crossmatch search engine parameter names.  In some search engines the "subject" is referred to as the "library" or "database" and most of the time maps to the larger dataset.  The assignment of these two may also have an impact on the number of hits returned ( multiple high scoring pairs vs single best hit etc ).  In RepeatMasker the "query" is the genomic sequence batch (small portion of the input sequence) and the repeat library is the "subject".  For RepeatModeler there is no specific meaning to the assignment since this is an all-vs-other genomic comparison.  One last thing of note: In the case of RMBlast the subject is the dataset which needs to be pre-formatted as a frozen database prior to the search.

Other parameters:

setMinScore == Sets the following:
           -xdrop_ungap = minScore * 2
           -xdrop_gap_final = minScore * 4
           -xdrop_gap = int( minScore / 2 )
           -min_raw_gapped_score = minScore 
           "-dust no"

setMatrix == -matrix /path/to/RepeatModeler/Matrices/ncbi/nt/comparison.matrix
setGenerateAlignments == Just tells the RepeatMasker object not to throw out this data returned by RMBlast by default.
setGapInit == -gapopen
setBandwidth == This is primarily a Crossmatch parameter but if its set to any value it will override the -xdrop_gap_final parameter and set it to = minScore (without the multiplier).
setInsGapExt == -gapextend
setDelGapExt == Ignored since RMBlast cannot distinguish between these two cases while Crossmatch can.
setMinMatch == -word_size
setScoreMode( SearchEngineI::complexityAdjustedScoreMode ) == -complexity_adjust
setMaskLevel == -mask_level

setAdditionalParameters == additional command-line arguments to rmblastn
     -gilist == -gilist
     dbslice == Only search a portion of the frozen database
     -gapW == This one I need to go back and look at in the NCBI Blast source code since a quick web search doesn't show it documented by them either.  

Please let me know if you have further questions.  I will leave this open until I find the gapW answer.

**Comment by darencard** [comment]
Thank you so much for the prompt and thorough response! Very useful information.

Regarding gapW, I looked further and it appears to be a WU Blast parameter reflecting window width for gapped alignments. I think I misread the code before, as it doesn't appear to be used with NCBI.
