### ISSUE TITLE
RepeatModeler configuration error

### ISSUE THREAD

**Issue by MattHuff** [rmhubley/RepeatModeler#6]
When I attempt to run RepeatModeler's configure script, I am running into an error in the installation paths. It asks me for the location of the NSEG program, which I provide, and provides me with this error:

```NSEG_directory does not appear to contain the trf program.```

This error also appears when I provide it the location of the trf program, or when I put a trf program into the NSEG directory. Has this been an issue for anyone else, and is there a way to get around this error?

**Comment by rmhubley** [comment]
Hi Matt,

  Sorry for this confusing error message.  It is indeed searching for the "nseg" program file in the directory that you specify.  The error message should have said "nseg" instead of "trf".  I have corrected this in the repository.  If you have specified the path to the parent directory containing the "nseg" program and you are still getting this message please let me know. 

-R
